Fix for entities with "link" attribute
It should be possible to use ressources with attribute named "link". Previously this would cause hal to crash: hal.js:106 : if (uri) this.link(new Link('self', uri)); 
with link is not a function exception. Renaming link function to _link solves this issue.